Feature/copy project name in report
doubleSlashde/KeepTime pull request #166
Opened 2023-09-18 13:21 UTC by DavidDamke

#158

2023-09-19 20:02 UTC, Death111 requested changes

2023-09-19 20:02 UTC, Death111 commented on src/main/java/de/doubleslash/keeptime/view/ReportController.java
> +         projectButtonBox.getChildren().add(createCopyProjectNameButton(onlyCurrentProjectWork));
why pass work items from the project instead of the project name directly?

2023-09-19 20:02 UTC, Death111 commented on src/main/java/de/doubleslash/keeptime/view/ReportController.java
> +         final ProjectReport pr = new ProjectReport();
don't think we need a project report for a single string

2023-09-19 20:02 UTC, Death111 commented on src/main/java/de/doubleslash/keeptime/common/Resources.java
> +      COPY_PROJECT_NAME("/svgs/copy.svg")
- inconsistent naming to other .svgs
- inconsitent formatting compared to other constants
- also please put the new svg to the other svgs

2023-10-13 12:43 UTC, DavidDamke commented on src/main/java/de/doubleslash/keeptime/view/ReportController.java
> +         projectButtonBox.getChildren().add(createCopyProjectNameButton(onlyCurrentProjectWork));
changed it so, now only the name gets passed

2023-10-13 12:43 UTC, DavidDamke commented on src/main/java/de/doubleslash/keeptime/view/ReportController.java
> +         final ProjectReport pr = new ProjectReport();
removed it

2023-10-13 12:43 UTC, DavidDamke commented on src/main/java/de/doubleslash/keeptime/common/Resources.java
> +      COPY_PROJECT_NAME("/svgs/copy.svg")
changed it to match the other SVGs

2023-10-24 07:34 UTC, Death111 requested changes

2023-10-24 07:34 UTC, Death111 commented on src/main/java/de/doubleslash/keeptime/view/ReportController.java
> +         projectButtonBox.getChildren().add(createCopyProjectNameButton(onlyCurrentProjectWork.get(0).getProject().getName()));
I'd say using the project name directly is easier and also more readable. What do you think?
```suggestion
         projectButtonBox.getChildren().add(createCopyProjectNameButton(project.getName()));
```

2023-10-25 15:48 UTC, Death111 commented on src/main/java/de/doubleslash/keeptime/view/ReportController.java
> +      final Button copyNotesButton = new Button("", SvgNodeProvider.getSvgNodeWithScale(RESOURCE.SVG_CLIPBOARD, 0.03, 0.03));
When using it the new icon feels more like "copy all child items" for me, as it has multiple instances

![image](https://github.com/doubleSlashde/KeepTime/assets/5772511/4c4ea8db-fc4b-4e8a-b45a-4635ed3df9fa)

what do you think? I think I would exchange the icons. So the "clipboard" copies the current row and the "multiple clipboards" copies the children.

2023-11-03 13:03 UTC, DavidDamke commented on src/main/java/de/doubleslash/keeptime/view/ReportController.java
> +      final Button copyNotesButton = new Button("", SvgNodeProvider.getSvgNodeWithScale(RESOURCE.SVG_CLIPBOARD, 0.03, 0.03));
Switched the functionality.
Changed the Svg name to match the displayed svg

2023-11-06 21:14 UTC, Death111 approved these changes

2023-11-06 21:15 UTC, merged